before_script:
  - nuget restore -NonInteractive

stages:
  - build

job:
  stage: build
  script:
  - echo "Release build..."
  - cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "build.proj" " && exit %%ERRORLEVEL%%
  tags: 
  except:
  - tags