//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("5.0.0.1011")]
[assembly: System.Reflection.AssemblyFileVersion("5.0.0.1011")]
[assembly: System.Reflection.AssemblyInformationalVersion("%version% hash:%shorthash%")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Denxorz, 2016")]


