// <auto-generated />
using HotChocolatey.Model.Save;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HotChocolatey.Migrations
{
    [DbContext(typeof(ListContext))]
    [Migration("20171005201406_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HotChocolatey.Model.Save.InstalledPackage", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int>("WorkStationId");

                    b.HasKey("Id", "WorkStationId");

                    b.HasIndex("WorkStationId");

                    b.ToTable("InstalledPackages");
                });

            modelBuilder.Entity("HotChocolatey.Model.Save.WorkStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("UniqueId");

                    b.HasKey("Id");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("HotChocolatey.Model.Save.InstalledPackage", b =>
                {
                    b.HasOne("HotChocolatey.Model.Save.WorkStation", "WorkStation")
                        .WithMany("InstalledPackages")
                        .HasForeignKey("WorkStationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
